### PR TITLE
configure.ac: run autoupdate

### PR DESCRIPTION
**Pull request by orlitzky**
Two minor changes that the "autoupdate" program suggests:

* Quote the arguments to `AC_INIT`
* Replace `AC_PROG_LIBTOOL` with `LT_INIT`

### CODE REVIEW

**Comment by wbkboyer** [comment]
I'll take a look at this; I need to double-check if this resolves the warnings from #46 !

**Comment by orlitzky** [comment]
It should resolve the warning about `AC_PROG_LIBTOOL` at least. Square brackets are quotes in m4, so adding those should be harmless, and according to the documentation, `LT_INIT` is simply the new name for the `AC_PROG_LIBTOOL` macro: https://www.gnu.org/software/libtool/manual/html_node/LT_005fINIT.html#index-LT_005fINIT

**Comment by orlitzky** [comment]
> 1. Rearrange commands in [autogen.sh](http://autogen.sh/) so libtool --copy would come first and we have the m4 directory populated before calling aclocal and autoconf (resolve warnings on Windows)
> 3. Additional sources indicate it might be a good practice to add [autoreconf -ivf](https://stackoverflow.com/a/32003575/5456879) to autogen.sh.

Unless you are doing something weird (and you aren't), it should suffice to put **only** `autoreconf -fi` inside `autogen.sh`. The autoreconf program is a wrapper around all of the other stuff in there, so you don't have to remember five separate programs to run and the correct order to run them in. But I also have no experience on Windows, so who knows.

> 2. Add AC_CONFIG_MACRO_DIRS([m4]) to configure.ac and ACLOCAL_AMFLAGS = -I m4 to Makefile.am

This isn't a warning _per se_. If you are using any local macros, normally they get concatenated into an `aclocal.m4` that is shipped with your program.  If you add those two lines, though, your local macros will instead get placed in the `m4` directory and shipped separately (`aclocal.m4` will `m4_include` them). It's a little nicer for people who want to edit the macros, but you don't have any local macros besides the libtool boilerplate.

So it's up to you. Adding them makes the suggestion go away, but leaves you with an empty `m4` directory in your source tree that technically doesn't need to be there. Which is more annoying?

**Review by wbkboyer — APPROVED** [review]
Heck yeah, this is great; I just double checked, and replacing the existing contents of `autogen.sh` with only the command `autoreconf -fi` works as expected on Windows 10 (MinGW32) and Debian 12.7, but I'll leave that for a follow-up PR! 💪🏼 

Thank you as always for your contributions and knowledge-share, @orlitzky; you're an absolute rockstar!! 🚀

**Pull request merged**
